[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
board_build.partitions = partitions.csv
board_upload.flash_size = 8MB
board_build.flash_size = 8MB
lib_deps =
  bblanchon/ArduinoJson @ ^7.3.0
extra_scripts = post:scripts/merge_firmware.py
